### ISSUE TITLE
Removing jcenter() error in build

### ISSUE THREAD

**Issue by techker** [VMadalin/easypermissions-ktx#4]
## Basic Information

Device type:Android
OS version: 11
EasyPermissions version: all

## Describe the problem

With the new Android X JCenter() is now deprecated. when removing it fro gradle we get
 Failed to resolve: com.vmadalin:easypermissions-ktx:0.1.0

## Code and logs

Failed to resolve: com.vmadalin:easypermissions-ktx:0.1.0
Show in Project Structure dialog
Affected Modules: app

// TODO(you): show the code that produces the problem,
//            and any relevant logs.
```

**Comment by VMadalin** [comment]
Hi @techker thank you for the ticket. I created a branch with the changes https://github.com/VMadalin/easypermissions-ktx/tree/migrate-to-maven-central and soon as I have everything in place to publish to `maven central` I gonna create the PR.

**Comment by techker** [comment]
great thx!
